/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;


import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nicho
 */
public class ForgetPassword extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form ForgetPassword
     */
    public ForgetPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        hide = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        resetbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        securityq = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        answertxt = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true), "Forget Password", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 48), new java.awt.Color(0, 153, 255))); // NOI18N
        jPanel3.setLayout(null);

        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User/icon/hideeye.png"))); // NOI18N
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hideMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hideMouseReleased(evt);
            }
        });
        jPanel3.add(hide);
        hide.setBounds(630, 320, 32, 38);

        show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User/icon/showeye.png"))); // NOI18N
        jPanel3.add(show);
        show.setBounds(630, 320, 32, 38);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("New Password");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(70, 330, 110, 28);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Username");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(100, 130, 80, 33);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User/icon/icons8_user_30px.png"))); // NOI18N
        jPanel3.add(jLabel9);
        jLabel9.setBounds(200, 130, 30, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User/icon/icons8_lock_30px_1.png"))); // NOI18N
        jPanel3.add(jLabel8);
        jLabel8.setBounds(200, 320, 30, 40);

        txtuser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtuser.setToolTipText("Enter your UserName.");
        jPanel3.add(txtuser);
        txtuser.setBounds(240, 120, 370, 38);

        txtPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPassword.setToolTipText("Enter your Password.");
        jPanel3.add(txtPassword);
        txtPassword.setBounds(240, 320, 370, 38);

        resetbtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        resetbtn.setForeground(new java.awt.Color(51, 51, 51));
        resetbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User/icon/passrest.png"))); // NOI18N
        resetbtn.setText("Reset Your Password");
        resetbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });
        jPanel3.add(resetbtn);
        resetbtn.setBounds(290, 390, 240, 60);

        backbtn.setBackground(new java.awt.Color(102, 102, 102));
        backbtn.setForeground(new java.awt.Color(102, 102, 102));
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User/icon/backico.png"))); // NOI18N
        backbtn.setBorder(null);
        backbtn.setBorderPainted(false);
        backbtn.setFocusPainted(false);
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel3.add(backbtn);
        backbtn.setBounds(700, 440, 63, 63);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Security Question");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(50, 200, 130, 33);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User/icon/icons8_poll_30px.png"))); // NOI18N
        jPanel3.add(jLabel10);
        jLabel10.setBounds(200, 200, 30, 30);

        securityq.setEditable(false);
        securityq.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        securityq.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        securityq.setToolTipText("");
        jPanel3.add(securityq);
        securityq.setBounds(240, 190, 370, 38);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Answer");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(120, 260, 60, 33);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User/icon/icons8_stack_exchange_answer_30px.png"))); // NOI18N
        jPanel3.add(jLabel11);
        jLabel11.setBounds(200, 260, 30, 30);

        answertxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        answertxt.setToolTipText("Enter your Answer.");
        jPanel3.add(answertxt);
        answertxt.setBounds(240, 250, 370, 38);

        searchbtn.setBackground(new java.awt.Color(204, 204, 204));
        searchbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User/icon/icons8_search_30px.png"))); // NOI18N
        searchbtn.setToolTipText("Search");
        searchbtn.setBorder(new javax.swing.border.MatteBorder(null));
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel3.add(searchbtn);
        searchbtn.setBounds(640, 120, 40, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        // TODO add your handling code here:
        LoginForm l = new LoginForm();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnMouseClicked

    private void hideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMousePressed
        show.setVisible(true);
        hide.setVisible(false);
        txtPassword.setEchoChar((char)0);

    }//GEN-LAST:event_hideMousePressed

    private void hideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseReleased
        show.setVisible(false);
        hide.setVisible(true);
        txtPassword.setEchoChar('\u25CF');
    }//GEN-LAST:event_hideMouseReleased

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        String username=txtuser.getText();
        String newPassword=txtPassword.getText();
        String answer=answertxt.getText();
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin", "root", "");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("SELECT * FROM `multiuserlogin` WHERE username='"+username+"' AND securityAns='"+answer+"'");
            if(rs.next()){
                st.executeUpdate("UPDATE `multiuserlogin` SET password='"+newPassword+"' WHERE username='"+username+"' AND securityAns='"+answer+"'");
                JOptionPane.showMessageDialog(this,"Password change successfully!");
                getToolkit().beep();
                LoginForm l = new LoginForm();
                l.setVisible(true);
                this.setVisible(false);
            }else{
                getToolkit().beep();
                JOptionPane.showMessageDialog(null,"Plese Enter correct Username or Answer and Try Again!");
            }
            con.close();
        }catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_resetbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        String username=txtuser.getText();
        try{
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/multiuserlogin", "root", "");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("SELECT securityQ FROM `multiuserlogin` WHERE username='"+username+"'");
            if(rs.next()){
                securityq.setText(rs.getString(1));
            }else{
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Please Enter correct username.");
                con.close();
                rs.close();
            }
        }catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answertxt;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel hide;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField securityq;
    private javax.swing.JLabel show;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
